# version: '3.8'

# services:
#   rabbitmq:
#     image: rabbitmq:4-management
#     container_name: rabbitmq-broker
#     ports:
#       - "5672:5672"
#       - "15672:15672"
#     environment:
#      - RABBITMQ_ERLANG_COOKIE=secret_cookie_string_must_be_long
#       - RABBITMQ_DEFAULT_USER=guest
#       - RABBITMQ_DEFAULT_PASS=guest
#     restart: unless-stopped
#   zipkin:
#     image: openzipkin/zipkin
#     container_name: zipkin-server
#     ports:
#       - "9411:9411"